name: Build Image

on:
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO_NAME: eshijii/terraform-tools
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build image
      run: docker build . --file Dockerfile --tag ${{env.DOCKERHUB_REPO_NAME}}:${{env.IMAGE_TAG}}
