name: Unit tests

on:
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO_NAME: eshijii/terraform-tools
  IMAGE_TAG: latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v1
      with:
        go-version: 1.25
    - name: Install dependencies (if any)
      run: |
        sudo apt-get update && sudo apt-get install -y make gcc
        # Example: Install build tools or test runners
    - name: Run Go Tests
      # working-directory: test
      run: make test
    - name: Read VERSION file
      id: getversion
      run: |
        cat version
        echo "version=$(cat version)" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: make build
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{env.DOCKERHUB_REPO_NAME}}:${{env.IMAGE_TAG}}
        docker tag ${{env.DOCKERHUB_REPO_NAME}}:${{env.IMAGE_TAG}} ${{env.DOCKERHUB_REPO_NAME}}:${{ steps.getversion.outputs.version }}


