name: Docker Push Image

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Read VERSION file
      id: getversion
      run: |
        cat version
        echo "version=$(cat version)" >> $GITHUB_OUTPUT

    - name: Set Image Tag
      id: setImageTag
      run: |
        echo "IMAGE_TAG=${{env.DOCKERHUB_REPO_NAME}}:${{ steps.getVersion.outputs.version }}" >> $GITHUB_ENV

    - name: docker login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.setImageTag.outputs.IMAGE_TAG }}

    - name: DockerPush
      run: docker push ${{ steps.setImageTag.outputs.IMAGE_TAG }}
