name: Docker Push Image

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO_NAME: eshijii/terraform-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Read version file
      run: |
        cat version
        echo "VERSION=$(cat version)" >> $GITHUB_ENV

    - name: Set image tag
      run: |
        echo "IMAGE_TAG=${{env.DOCKERHUB_REPO_NAME}}:$VERSION" >> $GITHUB_ENV

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Create tag latest
      run: docker tag $IMAGE_TAG ${{env.DOCKERHUB_REPO_NAME}}:latest

    - name: Push image
      run: |
        docker push $IMAGE_TAG
        docker push ${{env.DOCKERHUB_REPO_NAME}}:latest
