name: Docker Push Image

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO_NAME: eshijii/terraform-docker

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Read VERSION file
      run: |
        cat version
        echo "VERSION=$(cat version)" >> $GITHUB_ENV

    - name: Set Image Tag
      run: |
        echo "IMAGE_TAG=${{env.DOCKERHUB_REPO_NAME}}:$VERSION" >> $GITHUB_ENV

    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: DockerPush
      run: docker push $IMAGE_TAG
