name: Unit tests

on:
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO_NAME: eshijii/terraform-tools
  IMAGE_TAG: latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v1
      with:
        go-version: 1.25
    - name: Run Go Tests
      working-directory: test
      run: make test
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.DOCKERHUB_REPO_NAME}}:${{env.IMAGE_TAG}}


